add docs for compute viscosity functions
JuliaGeodynamics/GeoParams.jl pull request #120
Opened 2023-10-18 13:46 UTC by tduretz

2023-10-18 14:27 UTC, albert-de-montserrat commented
Thanks for the contribution @tduretz  ! 

It'd be great if you could add a MarkDown file in the `docs/src/man` folder as well.  And add it to the list in `docs/make.jl`.

2023-10-18 14:28 UTC, albert-de-montserrat requested changes

2023-10-18 14:28 UTC, albert-de-montserrat commented on src/Viscosity/Viscosity.jl
> +Compute effective viscosity given a 2nd invariant of the deviatoric strain rate tensor and an extra paramaters undet the from of a named tuple, e.g., (;T=T)
Typos

2023-10-18 14:28 UTC, albert-de-montserrat commented on src/Viscosity/Viscosity.jl
> +
Typos

2023-10-18 15:26 UTC, tduretz commented on src/Viscosity/Viscosity.jl
> +Compute effective viscosity given a 2nd invariant of the deviatoric strain rate tensor and an extra paramaters undet the from of a named tuple, e.g., (;T=T)
fixed

2023-10-18 15:26 UTC, tduretz commented on src/Viscosity/Viscosity.jl
> +
fixed

2023-10-19 08:17 UTC, albert-de-montserrat approved these changes
Great thanks! Looks ready to be merged.

2023-10-19 08:17 UTC, merged